<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

return '
    {
    "tabla5": {
        "sectorFinanciero": {
            "50RE": "50/50 Redescuento",
            "APAG": "Acuerdo",
            "AEXC": "Asociado Excelente",
            "BACO": "Banca Comunal",
            "BISE": "Bienes Y Servicios",
            "BISO": "Bienestar Social",
            "CALA": "Calamidad",
            "CALK": "Credialkosto",
            "CALP": "Creditos ALP",
            "CCAR": "Compra Cartera",
            "CCFU": "Compra de cafÃ© a futuro",
            "CCON": "Celulares Conexel",
            "CEXI": "Crediexito",
            "CDFA": "CREDIFACIL",
            "CRSI": "CREDITO SI",
            "CFEN": "CapitalizaciÃ³n Fomento Entidades",
            "CFID": "Comisiones De Fideicomiso",
            "CICG": "Cartera ordinaria ICG",
            "CNXC": "Conexel",
            "CRLZ": "Consolidado Rotativo Libranza",
            "CONS": "Consumo",
            "CONT": "Constructor",
            "CPRI": "Credi-Prima",
            "CRAP": "CredirÃ¡pido",
            "CROT": "Consolidado Rotativo",
            "CDEM": "Comercial Desarrollo Empresarial",
            "COMT": "Comercial Tesoreria",
            "CALP": "CrÃ©ditos ALP",
            "CCON": "Crediconsumo",
            "CEMP": "Crediempresa",
            "CNEG": "Credinegocios",
            "CDBM": "Creditos de Bajo Monto",
            "CRSI": "CrÃ©dito SI",
            "CSAL": "CrÃ©dito de Salud",
            "CYA": "Credi-Ya",
            "CORE": "Con Recurso",
            "EDEX": "Educativo del Exterior",
            "EDUC": "Educativo",
            "EMER": "Emergente",
            "EMPL": "Empleado",
            "ENOA": "Empleados no Asociados",
            "ESPC": "Especializaciones",
            "EXLI": "Exito Libre InversiÃ³n",
            "EXNO": "Exito Normal",
            "EXVH": "Exito VehÃ­culo",
            "FACT": "Factoring",
            "FAGU": "Fondo del Agua",
            "FDPT": "Fomento Departamento",
            "FEFU": "Fertifuturo",
            "FENT": "Fomento Entidades",
            "FIDU": "Fiduciaria",
            "FGRO": "Finagro",
            "FMUN": "Fomento Municipios",
            "FOGA": "Fogafin",
            "FSEG": "FinanciaciÃ³n De Seguros",
            "GFNG": "GarantÃ­as Pagadas al Fondo Nacional de GarantÃ­as",
            "GRUP": "Grupal",
            "GSOL": "Grupo Solidario",
            "HOSP": "HospitalizaciÃ³n",
            "IDON": "IdÃ³nea",
            "INDV": "Individual",
            "INMD": "Inmediato",
            "ICDC": "Insumos Cultivos de Cafe",
            "LAPA": "Leasing Apalancado",
            "LBAC": "Lease-Back",
            "LCEN": "Linea Caf Entidades",
            "LCMU": "Linea Caf Municipios",
            "LEAS": "Leasing",
            "LEXP": "Leasing de ExportaciÃ³n",
            "LEXS": "Leasing de ExportaciÃ³n Sindicado",
            "LFIN": "Leasing Financiero",
            "LFIS": "Leasing Financiero Sindicado",
            "LIBZ": "Libranza",
            "LBAG": "Libranza Agropecuario",
            "LBCC": "Libranza Compra de Cartera",
            "LBCL": "Libranza Calamidad",
            "LBCO": "Libranza Comercio",
            "LBCF": "Libranza Coonfisocial",
            "LICN": "Libranza Credito NavideÃ±o",
            "LBDE": "Libranza Destinacion Especifica",
            "LBED": "Libranza Educativo",
            "LBEE": "Libranza Educativo en el Exterior",
            "LBEG": "Libranza Emergente",
            "LBEM": "Libranza Empleado",
            "LBFS": "Libranza FinanciaciÃ³n de Seguros",
            "LBIN": "Libranza Industria",
            "LBLD": "Libranza Libre Destino",
            "LBLI": "Libranza Libre InversiÃ³n",
            "LBMB": "Libranza Viaje Mundial Brasil",
            "LBME": "Libranza Muebles y Enseres",
            "LBMC": "Libranza Microcredito",
            "LBNO": "Libranza Normal",
            "LMOF": "Libranza Oficial",
            "LBOR": "Libranza Ordinario",
            "LBPD": "Libranza Pago de Deudas",
            "LBRC": "Libranza RecreaciÃ³n",
            "LBRM": "Libranza Reestructuraciones por Mora",
            "LBRT": "Libranza Rotativo",
            "LBSA": "Libranza Salud",
            "LBSM": "Libranza Suministro",
            "LBVH": "Libranza VehÃ­culo",
            "LBVI": "Libranza Vivienda",
            "LIMP": "Leasing de ImportaciÃ³n",
            "LIMS": "Leasing de ImportaciÃ³n Sindicado",
            "LINF": "Leasing de Infraestructura",
            "LINM": "Leasing Inmobiliario",
            "LINS": "Leasing Internacional Sindicado",
            "LINT": "Leasing Internacional",
            "LINV": "Libre InversiÃ³n",
            "LMUN": "Leasing Municipal",
            "LOPE": "Leasing Operativo",
            "LOPS": "Leasing Operativo Sindicado",
            "LSIN": "Leasing Sindicado",
            "LHAB": "Leasing Habitacional",
            "MYPE": "Micros y PequeÃ±as Empresas",
            "MEXT": "Moneda Extranjera",
            "NMCY": "Nuevo Milenio Crediya Seccional",
            "NMIL": "Nuevo Milenio",
            "NORM": "Normal",
            "OCPR": "Ã?rdenes de Compra",
            "OICG": "Otros ICG",
            "OPLZ": "Operaciones a Plazo",
            "ORDI": "Ordinario",
            "ORES": "Operaciones Respo",
            "OSIM": "Operaciones Simultaneas",
            "OTRO": "Otro",
            "PAGD": "Pago de Deudas",
            "PESP": "Pago en Especie",
            "PENS": "Pensionado",
            "PPCR": "Prestamo Personal Credifacil",
            "PIGN": "PignoraciÃ³n",
            "RECR": "RecreaciÃ³n",
            "REDE": "Redescuento",
            "REES": "Reestructurados",
            "REPL": "Reparaciones Locativas Y Mejoras De Vivienda",
            "RFCA": "Redescuento Findeter Capitalizado",
            "RFEN": "Redescuento Findeter Entidades",
            "RFMU": "Redescuento Findeter Municipios",
            "ROTA": "Rotativo",
            "SAME": "PolÃ­tica de saldos menores banco de BogotÃ¡",
            "SARR": "Servicio de Arrendamiento",
            "SIRE": "Sin Recurso",
            "SICG": "Sobregiro ICG",
            "SOBR": "Sobregiro",
            "SOLI": "Solidario",
            "SUBL": "Subleasing",
            "SUEM": "Sufi Empleado",
            "SULE": "Sufi Leasing",
            "SULI": "Sufi Libre InversiÃ³n",
            "SULM": "Sufi Leasing de ImportaciÃ³n",
            "SUMI": "Suministro",
            "SUNO": "Sufi Normal",
            "SURO": "Sufi Rotativo",
            "SUVE": "Sufi VehÃ­culo",
            "TACN": "Taquilla Credito NavideÃ±o",
            "TADE": "Taquilla Destinacion Especifica",
            "TAMC": "Taquilla Microcredito",
            "TAOF": "Taquilla Oficial",
            "TARM": "Taquilla Reestructuraciones por Mora",
            "TCR": "Tarjeta De CrÃ©dito",
            "TESE": "TesorerÃ­a Entidades",
            "TESM": "TesorerÃ­a Municipios",
            "TITU": "Titularizadora",
            "TRNS": "Transitorio",
            "UNIV": "Universidad",
            "UROT": "UtilizaciÃ³n Rotativo",
            "VBIE": "Venta de Bienes",
            "VCAR": "Venta Cartera",
            "VEHI": "VehÃ­culo",
            "VCDC": "Vivienda Compra De Cartera",
            "VIS": "Vivienda de InterÃ©s Social",
            "VIVI": "Vivienda"
        },
        "sectorReal": {
            "AINM": "Arrendamiento Inmobiliario",
            "APOR": "Aportes Parafiscales",
            "ASES": "AsesorÃ­as",
            "CABL": "Cable",
            "CCAR": "Compra de Cartera",
            "CCMP": "Caja de CompensaciÃ³n",
            "CFAC": "Compra por Facturas",
            "CLUB": "Club Social",
            "CMPR": "Comparendos TrÃ¡nsito Y Transporte",
            "CPOS": "Cheques Posfechados",
            "CRED": "Cupo CrÃ©dito",
            "EMPL": "Empleado",
            "EMPR": "Empresarial",
            "FCON": "Facturas Consolidadas",
            "FGNV": "FinanciaciÃ³n Gnv",
            "FINS": "Fallos de InspecciÃ³n",
            "GASO": "Gasodomesticos",
            "HOTE": "HotelerÃ­a y turismo",
            "IEDU": "InstituciÃ³n Educativa",
            "IMPU": "Impuestos",
            "INET": "Internet",
            "INFR": "Infraestructura",
            "LIBZ": "Libranza",
            "LINV": "Libre InversiÃ³n",
            "LOGI": "Logistica",
            "MDIO": "Sector Medios",
            "MEDI": "Medidor",
            "MENS": "MensajerÃ­a especializada",
            "MTEC": "Multas RevisiÃ³n TÃ©cnico mecÃ¡nica",
            "MTPU": "Multas Empresas Transporte Publico",
            "NORE": "No Reportada",
            "NORM": "Normal",
            "PGRE": "PagarÃ©",
            "RECR": "RecreaciÃ³n",
            "RENT": "Renting",
            "ROTA": "Rotativo",
            "SAGU": "Servicio de Agua",
            "SALD": "Servicios de Salud",
            "SBEE": "Servicio Beeper",
            "SEGU": "Seguridad",
            "SENE": "Servicio EnergÃ­a",
            "SGAS": "Servicio de Gas",
            "SPUB": "Servicios PÃºblicos",
            "STEL": "Servicio TelÃ©fono",
            "SUSC": "Suscripciones",
            "TCEL": "TelefonÃ­a Celular",
            "TCIA": "TelÃ©fono Comercial",
            "TCR": "Tarjeta de CrÃ©dito Sector Real",
            "TELC": "Telecomunicaciones",
            "TELF": "TelÃ©fono",
            "TMER": "Transporte de Mercancias",
            "VCAR": "Venta de Cartera",
            "VEHI": "VehÃ­culo",
            "VIVI": "Vivienda",
            "VPRV": "Vigilancia Privada",
            "VEDI": "Venta directa",
            "VDAC": "Venta directa Acovedi",
            "VDAR": "Venta directa Acovedi rotativo",
            "SEPM": "Saldos Adeudados EPM",
            "TEMP": "Servicios Temporales de Personal",
            "RESF": "Responsabilidad Fiscal",
            "AINM": "Afianzamiento Inmobiliario",
            "ARRT": "Arrendamiento",
            "ALQE": "Alquiler de equipos para construcciÃ³n",
            "MSVE": "Monitoreo satelital vehicular",
            "LDSF": "Libranza de Servicios Funerarios",
            "SFUN": "Servicios Funerarios",
            "LISE": "Libranza",
            "LAAJ": "Libranza en Asesoria y Asistencia Juridica",
            "MCRES": "Microcredito",
            "SRDO": "Servicio de reparaciones domiliciarias",
            "FEQM": "Financiacion equipo movil",
            "CONS": "Consumo"
        },
        "sectorAsegurador": {
            "ACCP": "Accidentes Personales",
            "ACUI": "Acuicultura",
            "AGRI": "AgrÃ­cola",
            "AUTO": "AutomÃ³viles",
            "AVIA": "AviaciÃ³n",
            "BARR": "Bienes en Arrendamiento",
            "CCIA": "CrÃ©dito Comercia",
            "CDEB": "Corriente DÃ©bil",
            "CEXP": "CrÃ©dito Exporta",
            "CINS": "CrÃ©dito por Insolven",
            "CMPL": "Cumplimiento",
            "CVID": "Colectivo Vida",
            "DESE": "Desempleo",
            "ECOS": "Enfermedad Costo",
            "EQEL": "Equipo ElectrÃ³nico",
            "EQMA": "Equipo y Maquinaria",
            "ESCA": "Estabilidad y Calidad",
            "EXEQ": "Exequias",
            "GEDU": "Grupo Educativo",
            "GRAN": "Granizo",
            "HOGR": "Hogar",
            "IFAM": "Integral Familiar",
            "INCE": "Incendio",
            "JUDI": "Judicial",
            "LCES": "Lucro Cesante",
            "MANJ": "Manejo",
            "MCOM": "Multiriesgo Comercial",
            "MIND": "Multiriesgo Industrial",
            "MPET": "Minas Y PetrÃ³leos",
            "MROT": "Mont Y Rot Maq",
            "NCAS": "NavegaciÃ³n Y Casco",
            "OCIV": "Obras Civiles Termin",
            "OTRO": "Otro",
            "P100": "Pensiones Ley100",
            "PJUB": "Pensiones de Jubilacion",
            "PVOL": "Pensiones Voluntarias",
            "RCIV": "Responsabilidad Civil",
            "RCON": "Riesgo Contratista",
            "RMON": "Todo Riesgo Montaje",
            "RPRO": "Riesgos Profesionales",
            "SALU": "Salud",
            "SEMO": "Semovientes",
            "SOAT": "Soat",
            "SPRE": "Seguros PrevisiÃ³n",
            "SROY": "Seguro Contra Roya",
            "SUST": "SustracciÃ³n",
            "TERR": "Terremoto",
            "TITU": "TÃ­tulos",
            "TRAN": "Transporte",
            "VGRU": "Vida Grupo",
            "VIDR": "Vidrios",
            "Individual": "Vida"
        }
    },
    "tabla2": {
        "AVAL": "Avalista",
        "AMPA": "Amparada",
        "CODE": "Codeudor",
        "DASO": "Deudor asociado",
        "DNAS": "Deudor no asociado",
        "PRIN": "Principal",
        "ARRE": "Arrendatario",
        "DSOL": "Deudor solidario",
        "COAR": "Coarrendatario",
        "COOT": "Cootitular",
        "PROV": "Proveedor",
        "PAGA": "Pagador"
    },
    "tabla3": {        
        "VIGE": "Vigente",
        "SALD": "Saldado",
        "REES": "Reestructurada",      
        "RECU": "Recuperado",      
        "REAC": "Reactivado",
        "NREP": "No Reportado",
        "NORE": "No Renovado ",
        "L550": "Proceso Negociación Ley 550",
        "IRRE": "Irrecuperable",
        "DUDO": "Dudoso Recaudo", 
        "DIFI": "Difícil Cobro", 
        "CUNI": "Cancelada Unilateralmente", 
        "CVOL": "Cancelada Voluntariamente", 
        "CROB": "Cancelada Extravió O Robo", 
        "CONT": "Contingencia", 
        "CONC": "Concordato", 
        "CMOR": "Cancelada Deuda Morosa", 
        "CMMM": "Cancelado Mal Manejo Por Mora", 
        "CMAL": "Cancelada Mal Manejo", 
        "CFAL": "Cancelada Fallecimiento", 
        "CVTE": "Cancelada Voluntariamente Por Un Tercero", 
        "CAST": "Castigada", 
        "1116": "Proceso Reorganización Ley 1116",
        "LINS": "Ley 1564 de 2012 insolvencia PNNC",
        
        "VIGE": "Vigente",
        "SUSP": "Suspendida por la entidad",
        "SALD": "Saldada",
        "REFI": "Refinanciado",
        "RECU": "Cartera recuperada",
        "NORE": "No reportado",
        "L550": "Ley 550",
        "INAC": "Inactivo",
        "DUDO": "Dudoso recaudo",
        "CROB": "Cancelada por extravió robo",
        "CMOR": "Cancelada por mora",
        "CAST": "Castigada",
        "1116": "Ley 1116",
        "LINS": "Ley 1564 de 2012 insolvencia PNNC",
        "JURI": "Jurídico",
        "PREJ": "Prejurídico"
        }
}    
    ';
